name: Deploy to gh-pages

on:
  push:
    branches:
      - main  # El workflow se ejecuta al hacer push en main
  workflow_dispatch:

permissions:
  contents: write  # Necesario para hacer push a gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist  # Asegúrate de que sea la carpeta correcta

